apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.spec.service_name }}
  name: {{ .Values.spec.service_name }}
spec:
  {{- if not .Values.nginx.autoscaling.enabled }}
  replicas: {{ .Values.nginx.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.spec.service_name }}
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'false'
      labels:
        app: {{ .Values.spec.service_name }}
    spec:
      containers:
      - name: {{ .Values.spec.service_name }}
        image: "{{ .Values.nginx.deployment.image.repository }}:{{ .Values.nginx.deployment.image.tag }}"
        ports:
        - containerPort: {{ .Values.nginx.service.targetport }}
        resources:
          {{- toYaml .Values.nginx.deployment.resources | nindent 10 }}
