{{- if .Values.nginx.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.spec.service_name }}-ing
  labels:
    app: {{ .Values.spec.service_name }}
  annotations:
    {{- toYaml .Values.nginx.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.nginx.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.nginx.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.spec.service_name }}
                port:
                  number: 80
            path: {{ .Values.nginx.ingress.path }}
            pathType: {{ .Values.nginx.ingress.pathType }}
{{- end }}