---
{{- if .Values.ml_app.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.spec.module_name }}
  labels:
    app: {{ .Values.spec.module_name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.spec.module_name }}
  minReplicas: {{ .Values.ml_app.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.ml_app.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.ml_app.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.ml_app.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.ml_app.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.ml_app.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}