apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spec.service_name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.spec.service_name }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.jenkins.service.targetport }}
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.jenkins.service.targetport }}