"aws-load-balancer-controller":
  replicaCount: 2
  image:
    repository: amazon/aws-alb-ingress-controller
    tag: v2.4.3
    pullPolicy: IfNotPresent
  clusterName: cs-prod
  ingressClass: alb

  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::021313123950:role/aws-lb-controller-irsa-role
    name: aws-load-balancer-controller
    automountServiceAccountToken: true
