"aws-load-balancer-controller":
  replicaCount: 2
  image:
    repository: amazon/aws-alb-ingress-controller
    tag: v2.4.3
    pullPolicy: IfNotPresent
  clusterName: dev-demo
  ingressClass: alb

  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063544445412:role/aws-load-balancer-controller
    name: aws-load-balancer-controller
    automountServiceAccountToken: true
