{{- if .Values.spec.serviceaccount.enabled }}
apiVersion: 'external-secrets.io/v1beta1'
kind: ClusterSecretStore
metadata:
  name: secretstore-by-role
spec:
  provider:
    aws:
      service: SecretsManager
      # define a specific role to limit access
      # to certain secrets.
      # role is a optional field that
      # can be omitted for test purposes
      role: {{ .Values.spec.role }}
      region: {{ .Values.spec.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.spec.serviceaccount.name }}
            namespace: external-secrets
{{- end }}